<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta charset="UTF-8">
<meta name="HandheldFriendly" content="True" />
<meta name="MobileOptimized" content="300" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
<meta name="format-detection" content="telephone=no">
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE11"  />
<title><?php echo $this->translate('index_txt_83');?></title>
<style>
  .language{
          background: url("/www/images/flags/<?php echo $this->SetLanguageFlag();?>") no-repeat;
          border-radius: 23px;
          background-size: 49px 45px;
          
  }
#header .logo a{
	display:block;
	position:absolute;
	width:100%;
	height:100%;
	text-indent:-9999px;
	background-image:url(http://www.wa-app.com/www/images/<?php echo $this->translate('image_link_4');?>);
	background-repeat:no-repeat;
	background-size:100% 100%;
	}
</style>
<link href="<?php echo $this->makeUrl('/css/fonts.css');?>" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->makeUrl('/css/bootstrap.min.css');?>" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->makeUrl('/css/ui/jquery-ui.min.css');?>" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->makeUrl('/css/custom.css');?>" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->makeUrl('/css/stylesheet.css');?>" rel="stylesheet" type="text/css" />

<!--Javascripts--> 
<script type="text/javascript" src="<?php echo $this->makeUrl('/js/jquery-1.10.1.min.js');?>"></script> 
<script type="text/javascript" src="<?php echo $this->makeUrl('/js/jquery-ui.min.js');?>"></script> 
<script src="<?php echo $this->makeUrl('/js/owl.carousel.min.js');?>"></script> 
<script src="<?php echo $this->makeUrl('/js/jquery.validate.min.js');?>"></script> 
<?php
            $config = Zend_Controller_Front::getInstance()->getParam('bootstrap');
            $apiKey = $config->getOption("quickblox_details_new");
            $apiKey['app_id']=$apiKey['app_id'];//"9361";
            $apiKey['auth_key']=$apiKey['auth_key'];//"h4GL7ABbpGVTBgV";
            $apiKey['auth_secret']=$apiKey['auth_secret'];//"Lqf9MaZjuce9Cen";
?>
<script src="<?php echo $this->makeUrl('/js/quick_blox/quickblox(1).js') ?>"></script>
<script src="<?php echo $this->makeUrl('/js/quick_blox/plugins/chat/quickblox.chat.js') ?>"></script>
<script src="<?php echo $this->makeUrl('/js/quick_blox/js/jquery.timeago.js') ?>"></script>
<script src="<?php echo $this->makeUrl('/js/quick_blox/js/helpers.js') ?>"></script>
<script src="<?php echo $this->makeUrl('/js/quick_blox/js/chat.js') ?>"></script>
<script>
  jQuery.support.cors = true;
        var QBAPP = {
	appID: <?php echo $apiKey['app_id'];?>,
	authKey: '<?php echo $apiKey['auth_key'];?>',
	authSecret: '<?php echo $apiKey['auth_secret'];?>',
	publicRoom: 'public'
};
var chatConfig={
        server: 'chatwaapp.quickblox.com',
	muc: 'muc.chatwaapp.quickblox.com',
	bosh: 'http://chatwaapp.quickblox.com:5280',
	amazon: 'https://qb-wa-media.s3.amazonaws.com/'
}
</script>
</head>
<body class="logged">
<!--Main Wrapper Starts-->
<div class="wrapBody">
  <div class="mainWrapper"> 
    <!--Header Starts-->
    <header>
      <div class="container">
        <div class="row">
          <div class="col-sm-3">
            <div class="logo"><a href="/" title="WA-app"><img src="/new_images/logo.png" alt="" /></a></div>
          </div>
<!--          <div class="col-sm-3">
            <div class="logo2"> <a href="javascript:void(0);" target="_blank" title="Indiegogo campaign"><img src="/new_images/indiegogo.jpg" alt="" /></a> </div>
          </div>-->
          <?php if(isset($this->loggedUserRow)){?>
          <div class="col-sm-9 loginInfo">
            <ul class="userInfo">
                <li style="min-width:155px">
                   <span class="userPic">
                      <a href="#">
                          <img src="<?php if($this->loggedUserRow->userImage!=''){ echo $this->loggedUserRow->userImage;}else{ echo $this->makeUrl('/www/images/user_icon.png'); } ?>" alt="<?=$this->loggedUserRow->userFullName?>" title="<?=$this->loggedUserRow->userFullName?>"/>
                      </a>
                  </span><?php echo $this->loggedUserRow->userFullName ?>
                  <br />
                <?php echo $this->loggedUserRow->getCountryName(); ?>
              </li>
              <li class="flags"><a href="#"><img style="width: 45px;" src="/www/images/flags/<?php echo $this->SetLanguageFlag();?>" alt="English" title="English"></a>
                <div class="lanWrap">
                  <div class="lanButton" style="display:none;"><span class="icon"></span> English <span class="arrow"></span> </div>
                  <div class="lanBox">
                    <div class="lbTitle"><span class="icon"></span><?php echo $this->setActiveLanguage();?><span class="arrow"></span></div>
                    <div class="lanList">
                      <ul class="clearfix">
                        <li class="active"><a href="/chat/chat?l=en"><img src="/www/images/flags/en.gif" alt=""/> English</a></li>
                            <li><a href="?l=es"><img src="/www/images/flags/es.gif" alt=""/> Español</a></li>
                            <li><a href="?l=ar"><img src="/www/images/flags/ab.gif" alt=""/> العربية</a></li>
                            <li><a href="?l=de"><img src="/www/images/flags/de.gif" alt=""/> Deutsch</a></li>
                            <li><a href="?l=nl"><img src="/www/images/flags/nl.gif" alt=""/> Nederlands</a></li>
                            <li><a href="?l=it"><img src="/www/images/flags/it.gif" alt=""/> Italiano</a></li>
                            <li><a href="?l=pt_br"><img src="/www/images/flags/br.gif" alt=""/> Brasileiro</a></li>
                            <li><a href="?l=tr"><img src="/www/images/flags/tr.gif" alt=""/> Türkçe</a></li>
                            <li><a href="?l=id"><img src="/www/images/flags/id.gif" alt=""/> Bahasa Indonesia</a></li>
                            <li><a href="?l=zh_tw"><img src="/www/images/flags/mm.gif" alt=""/> 繁體中文</a></li>
                            <li><a href="?l=fr"><img src="/www/images/flags/fr.gif" alt=""/> Français</a></li>
                            <li><a href="?l=ja"><img src="/www/images/flags/jp.gif" alt=""/> 日本語</a></li>
                            <li><a href="?l=zh_cn"><img src="/www/images/flags/cn.gif" alt=""/> 简体中文</a></li>
                            <li><a href="?l=ko"><img src="/www/images/flags/ko.gif" alt=""/> 한국어</a></li>
                            <li><a href="?l=th"><img src="/www/images/flags/th.gif" alt=""/> ภาษาไทย</a></li>
                            <li><a href="?l=pl"><img src="/www/images/flags/pl.gif" alt=""/> Polski</a></li>
                            <li><a href="?l=vi"><img src="/www/images/flags/vn.gif" alt=""/> Tiếng Việt</a></li>
                            <li><a href="?l=cs"><img src="/www/images/flags/cz.gif" alt=""/> Česky</a></li>
                            <li><a href="?l=da"><img src="/www/images/flags/dk.gif" alt=""/> Dansk</a></li>
                            <li><a href="?l=lv"><img src="/www/images/flags/lv.gif" alt=""/> Latviešu</a></li>
                            <li><a href="?l=sk"><img src="/www/images/flags/sv.gif" alt=""/> Slovenčina</a></li>
                            <li><a href="?l=ro"><img src="/www/images/flags/ro.gif" alt=""/> Română</a></li>
                            <li><a href="?l=el"><img src="/www/images/flags/il.gif" alt=""/> Ελληνικά</a></li>
                            <li><a href="?l=bg"><img src="/www/images/flags/bg.gif" alt=""/> Български</a></li>
                            <li><a href="?l=hr"><img src="/www/images/flags/hr.gif" alt=""/> Hrvatski</a></li>
                            <li><a href="?l=ms"><img src="/www/images/flags/my.gif" alt=""/> Bahasa Melayu</a></li>
                            <li><a href="?l=sr"><img src="/www/images/flags/sb.gif" alt=""/> српски</a></li>
                            <li><a href="?l=ru"><img src="/www/images/flags/ru.gif" alt=""/> Pусский</a></li>
                            <li><a href="?l=fi"><img src="/www/images/flags/fi.gif" alt=""/> suomi</a></li>
                            <li><a href="?l=hu"><img src="/www/images/flags/hu.gif" alt=""/> Magyar</a></li>
                            <li><a href="?l=fa"><img src="/www/images/flags/fa.gif" alt=""/> فارسی</a></li>
                            <li><a href="?l=nb"><img src="/www/images/flags/no.gif" alt=""/> Norsk</a></li>
                            <li><a href="?l=mk"><img src="/www/images/flags/mk.gif" alt=""/> Македонски</a></li>
                            <li><a href="?l=ca"><img src="/www/images/flags/ct.gif" alt=""/> Català</a></li>
                        </ul>
                    </div>
                    <div class="lanFoot"><a href="#">Help translate WA-app into your language</a></div>
                  </div>
                </div>
              </li>
                        <li class="notifications"> 
                            <a class="notification_count_link" onclick="$('#is_append').val(0);updateNotificationTime();getNotification();$('#infoicon').css('display','none');$('#infoicon').html('');" onblur="" href="#notifications">
                             <img src="/new_images/info_btn.png" alt="">
                              <span id="infoicon" style="display: none;"></span>
                            </a> 
                <!--Drop Down Popup-->
                <input type="hidden" name="is_append" id="is_append" value="0" />
                <div id="inset_form" name="inset_form"></div>
                <div class="lib_popup" id="notifications">
                  <h4><span class="icon notify"></span><?php echo $this->translate('layout_txt_1');?></h4>
                  <div class="libp_list">
                    <div id="notificationlist">
                    </div>
                  </div>
                </div>
              </li>
              <li class="settings"> <a href="#settings"><img src="/new_images/settings_btn.png" alt="" /></a>
                <input type="hidden" name="is_append" id="is_append" value="0">
                <div class="lib_popup" id="settings">
                  <div class="libp_box">
                    <h4><?php echo $this->translate('layout_txt_2');?></h4>
                    <ul>
                        <li><a href="#"><?php echo $this->translate('layout_txt_3');?></a></li>
                        <li><a href="<?php echo $this->makeUrl('/help/terms') ?>"><?php echo $this->translate('index_txt_17');?></a></li>
                        <li><a href="<?php echo $this->makeUrl('/help/terms') ?>#privacy"><?php echo $this->translate('index_txt_18');?></a></li>
                        <li><a href="<?php echo $this->makeUrl('/help/faq') ?>"><?php echo $this->translate('index_txt_16');?></a></li>
                        <li><a href="#"><?php echo $this->translate('layout_txt_4');?></a></li>
                    </ul>
                  </div>
                </div>
              </li>
              <li><a href="<?php echo $this->makeUrl('/index/logout') ?>"><img src="/new_images/logout_btn.png" alt="" /></a></li>
            </ul>
          </div>
          
          <div class="col-xs-12">
            <nav>
              <div class="menuIcon"></div>
              <ul>
                    <li <?php if($this->menu == "CHAT"):?> class="active" <?php endif ?>><a href="<?php echo $this->makeUrl('/chat/chat') ?>"><?php echo $this->translate('layout_txt_11');?></a></li>
                    <li <?php  if($this->menu == "MYWA" ||  $this->menu == "LISTWA"):?> class="active" <?php endif ?> ><a href="<?php echo $this->makeUrl('/mywa') ?>"><?php echo $this->translate('layout_txt_6');?></a></li>
                    <li <?php if($this->menu == "FRIENDS"):?> class="active" <?php endif ?> ><a href="<?php echo $this->makeUrl('/friends') ?>"><?php echo $this->translate('layout_txt_8');?></a></li>
                    <li <?php if($this->menu == "TRUSTEES"):?> class="active" <?php endif ?> ><a href="<?php echo $this->makeUrl('/trustees') ?>"><?php echo $this->translate('layout_txt_7');?></a></li>
                    <li <?php if($this->menu == "TESTAMENT"): ?> class="active" <?php endif ?> ><a href="<?php echo $this->makeUrl('/testament') ?>"><?php echo $this->translate('layout_txt_9');?></a></li>
                    <li><a href="#"><?php echo $this->translate('layout_txt_10');?></a></li>
              </ul>
            </nav>
          </div>
        <?php } ?>
        </div>
      </div>
    </header>
    <!--Header Ends--> 
    

<!--Breadcrumb Starts-->
<!--<div class="breadcrumb clearfix">

</div>-->
<!--Breadcrumb Ends-->
    
    <!--Page Content Starts-->
    <div class="content clearfix terms">
      <?php echo $this->layout()->content ?>
    </div>
    <!--Page Content Starts--> 
  </div>
  <?php if($this->menu!='CHAT'){?>
 <!--Footer Starts-->
  <footer>
    <div class="fContent">
      <div class="container">
        <div class="row">
          <div class="col-sm-5">
            <h4><?php echo $this->translate('index_txt_12');?></h4>
            <p><strong>All-in-WA</strong> <?php echo $this->translate('index_txt_6');?>, <?php echo $this->translate('index_txt_6a');?>, <?php echo $this->translate('index_txt_6b');?> <?php echo $this->translate('index_txt_13');?> <a href="<?php echo $this->makeUrl('/help/features') ;?>"><?php echo $this->translate('index_txt_14');?>...</a></p>
          </div>
          <div class="col-sm-7">
            <div class="col-xs-4">
              <h4>All-in-WA</h4>
              <ul class="clearfix">
                <li><a href="<?php echo $this->makeUrl('/help/features') ;?>"><?php echo $this->translate('index_txt_15');?></a></li>
                <li><a target="_blank" href="<?php echo $this->makeUrl('/help/faq') ?>"><?php echo $this->translate('index_txt_16');?></a></li>
                <li><a target="_blank" href="<?php echo $this->makeUrl('/help/terms') ?>"><?php echo $this->translate('index_txt_17');?></a></li>
                <li><a target="_blank" href="<?php echo $this->makeUrl('/help/terms') ?>#privacy"<?php echo $this->translate('index_txt_18');?></a></li>
                <li><a href="#">Sitemap </a></li>
              </ul>
            </div>
            <div class="col-xs-4">
              <h4>Contact</h4>
              <ul class="clearfix">
                <li><a href="<?php echo $this->makeUrl('/help/contact') ?>"><?php echo $this->translate('index_txt_21');?></a></li>
                <li><a href="<?php echo $this->makeUrl('/help/aboutus') ?>"><?php echo $this->translate('index_txt_22');?></a></li>
                <li><a href="https://www.facebook.com/WAappbook" target="_blank"><?php echo $this->translate('index_txt_23');?></a></li>
                <li><a href="https://twitter.com/waapptweet" target="_blank"><?php echo $this->translate('index_txt_24');?></a></li>
              </ul>
            </div>
            <div class="col-xs-4">
              <h4><?php echo $this->translate('index_txt_25');?></h4>
              <ul class="clearfix">
                <li><a href="#"><?php echo $this->translate('index_txt_26');?></a></li>
                <li><a href="#"><?php echo $this->translate('index_txt_26a');?></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <p><a href="javascript:void(0)" onclick="popupOpen('signup')">&copy;</a> 2015 <a href="index">WA-media</a>. <?php echo $this->translate('index_txt_27');?></p>
        </div>
      </div>
    </div>
  </footer>
  <!--Footer Ends--> 
  <?php }?>
  
</div>
<audio id="new_message" controls style="display: none">
   <source  src="/www/audio/incoming.ogg" type="audio/ogg">
</audio> 
<button style="display: none" id="new_message_button" onclick="document.getElementById('new_message').play()">Play the Audio</button>           
    <input type="hidden"  id="string_to_change"> 
        <input type="hidden" id="chat_user_id" >
        <input type="hidden" id="login_user" value="<?php echo $this->loggedUserRow->userEmail;?>">
        <input type="hidden" id="login_user_id" value="<?php echo $this->loggedUserRow->quickBloxId;?>">
        <input type="hidden" id="chat_type" name="chat_type">
        <input type="hidden" id="chat_dialog_id" name="chat_dialog_id">
        <input type="hidden" id="current_user" value="<?php echo $this->loggedUserRow->userNickName;?>">
<script type="text/javascript">
        function shortTimeMessage(msg){
            
            $("#short_time_msg #msg").html(msg);
            $("#short_time_msg").removeClass("fade_out");
            $("#short_time_msg").addClass("fade_in");
            
            setTimeout( function(){ 
                $("#short_time_msg").addClass("fade_out");
                $("#short_time_msg").removeClass("fade_in");
             }
             , 3000 );
        }
        
        $(document).ready(function(){
            $("#short_time_msg .close").click(function(){
               $("#short_time_msg").addClass("fade_out");
               $("#short_time_msg").removeClass("fade_in");
            });
            
            //Language Opener with Icon
        $('body').on('click', function(lan){
                var target = $(lan.target);
                if(target.is('.flags img')){
                        $('.lanBox').stop(true,true).slideToggle('fast');
                }
                else{
                        $('.lanBox').stop(true,true).slideUp('fast');
                }
        }); 
            
        });
        
    </script>

<?php if($this->loggedUserRow){?> 
<script>
/***** After every 5 sec getNotificationCount() executes, check whether new notification arrived or not, if yes, show count. *****/
setInterval(function () {getNotificationCount()}, 2000);


  function confirmRequest(receiver_id){
       var config = {
      ssl: false,

    endpoints: {
      api: 'apiwaapp.quickblox.com',
      chat:'chatwaapp.quickblox.com',
      muc: 'muc.chatwaapp.quickblox.com',
     
    },
    chatProtocol: {
      bosh: "http://chatwaapp.quickblox.com:5280",
      websocket: 'ws://chatwaapp.quickblox.com:5290'
    },
    debug: true,
    timeout: 1000000
  };
  
  QB.init(QBAPP.appID, QBAPP.authKey, QBAPP.authSecret,config);
    // QuickBlox session creation
    QB.createSession(function (err, result) {
        if (err) {
            console.log(err.detail);
        } else {
            //changeInputFileBehavior();
            //updateTime();

           
        }
    });

 
       var user_jid = getJIDD('<?php echo $this->loggedUserRow->quickBloxId;?>');
  	QB.chat.connect({jid: user_jid, password: '12345678'}, function(err, roster) {
            console.log(roster);
            var contact_jid = getJIDD(receiver_id);
            QB.chat.roster.confirm(contact_jid, function() {
              console.log('Roster request accept');
          });
       

});

}

function getJIDD(id){
    var jid = id+"-"+QBAPP.appID+"@"+chatConfig.server
    return jid;
}

</script>
<?php } ?>

</body>
<script src="<?php echo $this->makeUrl('/js/custom.js');?>"></script> 
<script src="<?php echo $this->makeUrl('/js/jquery.jscrollpane.min.js');?>"></script> 
<script src="<?php echo $this->makeUrl('/js/jquery.mousewheel.js');?>"></script> 
<script src="<?php echo $this->makeUrl('/js/timepicki.js');?>"></script> 
<script src="<?php echo $this->makeUrl('/js/functions.js');?>"></script> 
<script src="<?php echo $this->makeUrl('/js/html5lightbox.js');?>"></script>
<!-- Created By Sarvesh 17 Aug 2015 Testament Common functions--> 
<script src="<?php echo $this->makeUrl('/js/testamentcommon.js');?>"></script> 
<?php if($_SERVER['REQUEST_URI'] == '/testament/witness-request-view'): ?>
<script src="<?php echo $this->makeUrl('/js/recorder.js');?>"></script>
<script src="<?php echo $this->makeUrl('/js/main.js');?>"></script>
<script src="<?php echo $this->makeUrl('/js/audiodisplay.js');?>"></script>
<script src="<?php echo $this->makeUrl('/js/jquery.signaturepad.js');?>"></script>
<link href="<?php echo $this->makeUrl('/css/jquery.signaturepad.css');?>" rel="stylesheet" type="text/css" />
<script>
  (function(window) {
    var $canvas,
        onResize = function(event) {
          $canvas.attr({
            height: 300,
            width: 300
          });
        };

    $(document).ready(function() {
      $canvas = $('canvas');
      window.addEventListener('orientationchange', onResize, false);
      window.addEventListener('resize', onResize, false);
      onResize();

      $('form').signaturePad({
        drawOnly: true,
        defaultAction: 'drawIt',
        validateFields: false,
        lineWidth: 0,
        output: null,
        sigNav: null,
        name: null,
        typed: null,
        clear: 'input[type=reset]',
        typeIt: null,
        drawIt: null,
        typeItDesc: null,
        drawItDesc: null
      });
    });
  }(this));
  </script>
<?php endif; ?>
<!---------------------------------------------------------------->
</html>


  
