<!doctype html><html><head><meta charset="utf-8"><title>SafeTrip</title></head><body style=" margin:0px; padding:0px; list-style:none; font-family:arial; background:#e1e1e1;"><table width="768" border="0" align="center" cellpadding="0" cellspacing="0">
<tr> <td style="height:10px;"></td></tr>
<tr><td style="background:#f8f8f8;"><table width="100%" border="0" cellspacing="0" cellpadding="0"><tr>
<td style="background:#fff; padding:20px 10px;"><table width="100%" border="0" cellspacing="0" cellpadding="0">
<tr><td align="right" style="text-align:right; font-size:24px; font-weight:bold;color:#ccc;">RESET YOUR PASSWORD</td>
</tr></table></td>
</tr> <tr><td height="200" valign="top" style=" padding:20px 20px 0px 20px; font-size:14px; color:#333; line-height:20px;">
<?php echo $this->translate('email_txt_3');?> <?php echo $this->name; ?> <?php echo $this->translate('email_txt_3b');?>,
<br>
To reset your password, please <a href="<?=$this->baseUrl?>/admin/resetpassword/email/<?=$this->usrEmail?>/code/<?=$this->code?>">click here</a> 
</td>
</tr>
<tr>
<td>&nbsp;</td>
</tr></table></td></tr><tr><td style="background:#fff; padding:10px; font-size:12px; padding-bottom:25px;">
please contact us at <a href="mailto:support@appxcel.com" target="_top">support@appxcel.com</a></td>
</tr><tr> <td style="height:10px;"></td></tr>

<tr>
<td>
<?php echo $this->translate('email_txt_7');?>,
</td>
</tr>
<tr>
<td>
<?php echo ucfirst($this->username); ?> <?php echo $this->translate('email_txt_8');?>
</td>
</tr>
</table></body></html>
