<!doctype html><html><head><meta charset="utf-8"><title>SafeTrip</title></head><body style=" margin:0px; padding:0px; list-style:none; font-family:arial; background:#e1e1e1;"><table width="768" border="0" align="center" cellpadding="0" cellspacing="0">
<tr> <td style="height:10px;"></td></tr>
<tr><td style="background:#f8f8f8;"><table width="100%" border="0" cellspacing="0" cellpadding="0"><tr>
<td style="background:#fff; padding:20px 10px;"><table width="100%" border="0" cellspacing="0" cellpadding="0">
<tr><td align="right" style="text-align:right; font-size:24px; font-weight:bold;color:#ccc;">Contact Us</td>
</tr></table></td>
</tr> <tr><td height="200" valign="top" style=" padding:20px 20px 0px 20px; font-size:14px; color:#333; line-height:20px;">

Please enter this code for rest password
<p>Name: <?php echo $this->name; ?></p>
<p>Email: <?php echo $this->email; ?></p>
<p>Description: <?php echo $this->description; ?></p>
<p>Phone No: <?php echo $this->conPhoneNo; ?></p>
<?php if($this->conDeviceType)
{?>
<p>Device Type: <?php echo $this->conDeviceType; ?></p>
<?php } if($this->conDeviceId)
{?>
<p>Device Id: <?php echo $this->conDeviceId; ?></p>
<?php }
if($this->conDeviceVersion)
{?>
<p>Device Version: <?php echo $this->conDeviceVersion; ?></p>
<?php }?>
</td>
</tr>
<tr>
<td>&nbsp;</td>
</tr></table></td></tr><tr><td style="background:#fff; padding:10px; font-size:12px; padding-bottom:25px;">
please contact us at <a href="mailto:support@wa-app.com" target="_top">support@wa-app.com</a></td>
</tr><tr> <td style="height:10px;"></td></tr>
<tr>
<td>
Thanks,
</td>
</tr>
<tr>
<td>
WA-app Team
</td>
</tr>
</table></body></html>
