<html>
<head>
<title>WA</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body bgcolor="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">


<table width="648" border="0" align="center" cellpadding="0" cellspacing="0" style="font-family:Arial, sans-serif;">
  <tbody>
    <tr>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td>
      	<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">,
          <tr>
            <td style="width:24px; height:110px;"><img src="<?php echo $this->baseUrl ?>/images/mailer_format_01.png" style="vertical-align: top;" width="24" height="110" alt=""></td>
            <td align="left" valign="middle" style="background:#e6e6e6; border-bottom:1px solid #c9c9c9; height:109px;">
            
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tr>
                  <td align="left" valign="middle" style="height:108px; width:60px;"><img src="<?php echo $this->baseUrl ?>/images/logo.png" width="233" height="60" alt=""/></td>
                  <td align="right">
                      <a href="#fr"><img src="http://wa-app.com/www/images/flags/fr.gif" /></a> 
                      &nbsp; <a href="#nl"><img src="http://wa-app.com/www/images/flags/nl.gif" /></a>
                      &nbsp; <a href="#de"><img src="http://wa-app.com/www/images/flags/de.gif" /></a> 
                      &nbsp; <a href="#jp"><img src="http://wa-app.com/www/images/flags/jp.gif" /></a>
                      <!--&nbsp; <a href="#it"><img src="http://wa.appstudioz.fr/www/images/flags/it.gif" /></a>
                      &nbsp; <a href="#ch"><img src="http://wa-app.com/www/images/flags/ch.gif" /></a>-->
                  </td>
                </tr>
            </table></td>
            <td style="width:24px; height:110px;"><img src="<?php echo $this->baseUrl ?>/images/mailer_format_03.png" width="24" height="110" style="vertical-align: top;" alt=""></td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td>
      
      	<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
          <tr>
            <td style="width:12px;">&nbsp;</td>
            <td style="background:#f2f2f2; padding:20px; font-size:16px; color:#333333; line-height:22px;">
            
                <p><?php echo $this->translate('email_txt_3');?> <span style="color:#0084b5"> <?php echo $this->friend_name; ?></span> <?php echo $this->translate('email_txt_3b');?>, </p>

            <p>
                <span style="color:#0084b5"><?php echo $this->from_name ?></span> <?php echo $this->translate('email_txt_13');?>!
            </p>
             <p>
                 <?php echo $this->translate('email_txt_14');?>:<br>
                <span style="color:#15c"><?php echo $this->baseUrl ?></span>
            </p>
            <p><?php echo $this->translate('email_txt_6');?><br>
			<a href="mailto:support@wa-app.com" style="color:#0084b5; text-decoration:none;">support@wa-app.com</a>
            </p>
            
             <p><?php echo $this->translate('email_txt_7');?>,  <br>
			<?php echo $this->translate('email_txt_8');?>.  
			</p>
            
            </td>
            <td style="width:15px;">&nbsp;</td>
          </tr>
        </table>
      
      </td>
    </tr>
    <tr>
      <td><img src="<?php echo $this->baseUrl ?>/images/mailer_format_07.png" width="648" height="113" style="vertical-align: top;" alt=""></td>
    </tr>
    
    <tr>
      <td>
      	<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
          <tr>
          	<td style="width:189px; height:119px;"><img src="<?php echo $this->baseUrl ?>/images/mailer_format_08.png" width="189" height="119" style="vertical-align: top;" alt=""></td>
			<td style="width:270px; height:91px;">
            	<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
                  <tr>
                    <td style="width:270px; height:91px;"><img src="<?php echo $this->baseUrl ?>/images/mailer_format_09.png" alt="" width="270" height="91" style="vertical-align: top;" usemap="#Map" border="0"></td>
                  </tr>
                  <tr>
                    <td style="width:270px; height:28px;"><img src="<?php echo $this->baseUrl ?>/images/mailer_format_11.png" width="270" height="28" style="vertical-align: top;" alt=""></td>
                  </tr>
                </table>
            </td>
            <td style="width:189px; height:119px;"><img src="<?php echo $this->baseUrl ?>/images/mailer_format_10.png" width="189" height="119" style="vertical-align: top;" alt=""></td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td>
        <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
          <tr>
            <td style="width:12px;">&nbsp;</td>
            <td style="background:#FFF; padding:20px; font-size:16px; color:#333333; line-height:22px;">
                <a name="fr"><img src="http://wa-app.com/www/images/flags/fr.gif" /></a>
                Cher <?php echo $this->friend_name; ?>,
<p><?php echo $this->from_name ?> souhaite vous ajouter comme ami!</p>
<p>S'il vous plaît suivez le lien suivant pour accepter ou rejeter:
<?php echo $this->baseUrl ?></p>
<p>Si vous avez des questions ou souhaitez nous contacter, vous pouvez nous rejoindre via <a href="mailto:support@wa-app.com" style="color:#0084b5; text-decoration:none;">support@wa-app.com</a></p>
<p>Merci,
L'équipe WA.</p>
                <br />
                
                <a name="nl"><img src="http://wa-app.com/www/images/flags/nl.gif" /></a>
                Beste <?php echo $this->friend_name; ?>,
<p><?php echo $this->from_name ?> wil je als WA-vriend toevoegen!</p>
<p>Volg AUB de volgende link om te accepteren of weigeren:
<?php echo $this->baseUrl ?></p>
<p>Indien u vragen heeft of contact met ons wilt opnemen, dan kunt u dat doen via <a href="mailto:support@wa-app.com" style="color:#0084b5; text-decoration:none;">support@wa-app.com</a></p>
<p>Bedankt,
Het WA team.</p>
                <br />
                <a name="de"><img src="http://wa-app.com/www/images/flags/de.gif" /></a>
                Lieber <?php echo $this->friend_name; ?>,
<p><?php echo $this->from_name ?> möchte dich als Freund hinzufügen!</p>
<p>Bitte folgen Sie den folgenden Link um anzunehmen oder abzulehnen:
<?php echo $this->baseUrl ?></p>
<p>Wenn Sie Fragen haben oder uns kontaktieren möchten, können Sie uns hier erreichen <a href="mailto:support@wa-app.com" style="color:#0084b5; text-decoration:none;">support@wa-app.com</a></p>
<p>Vielen Dank,
Die WA team.</p>
                <br />
                <a name="jp"><img src="http://wa-app.com/www/images/flags/jp.gif" /></a>
                親愛なる <?php echo $this->friend_name; ?>,
<p><?php echo $this->from_name ?> あなたを友達として追加したいです！</p>
<p>受け入れるか拒否するには、以下のリンクに従ってください。:
<?php echo $this->baseUrl ?></p>
<p>ご質問があるか、私達に連絡したい場合は、 <a href="mailto:support@wa-app.com" style="color:#0084b5; text-decoration:none;">support@wa-app.com</a> を介して私たちに到達することができます</p>
<p>おかげで、
WAチーム。</p>
                <br />
            </td>
            <td style="width:15px;">&nbsp;</td>
          </tr>
        </table>
      </td>
    </tr>
  </tbody>
</table>

<map name="Map"><area shape="circle" coords="184,27,21" href=mailto:"support@wa-app.com">
	<area shape="circle" coords="135,27,21" href="http://www.twitter.com/waapptweet">
    <area shape="circle" coords="85,27,21" href="http://www.facebook.com/waappbook">
</map>
</body>
</html>