<html>
<head>
<title>WA</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body bgcolor="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
<table width="648" border="0" align="center" cellpadding="0" cellspacing="0" style="font-family:Arial, sans-serif;">
  <tbody>
    <tr>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td>
      	<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">,
          <tr>
            <td style="width:24px; height:110px;"><img src="<?php echo $this->baseUrl ?>/images/mailer_format_01.png" style="vertical-align: top;" width="24" height="110" alt=""></td>
            <td align="left" valign="middle" style="background:#e6e6e6; border-bottom:1px solid #c9c9c9; height:109px;">
            
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tr>
                  <td align="left" valign="middle" style="height:108px; width:60px;"><img src="<?php echo $this->baseUrl ?>/images/logo.jpg" width="233" height="60" alt=""/></td>
                </tr>
            </table></td>
            <td style="width:24px; height:110px;"><img src="<?php echo $this->baseUrl ?>/images/mailer_format_03.png" width="24" height="110" style="vertical-align: top;" alt=""></td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td>
        <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
          <tr>
            <td style="width:12px;">&nbsp;</td>
            <td style="background:#f2f2f2; padding:20px; font-size:16px; color:#333333; line-height:22px;">
                <p>
                    <?php echo $this->userNickName; ?> has send WA-Track message for you. To see WA-Track message please login in WA-App using following link:<br>
                    <?php echo $this->baseUrl?>
                </p> 
                <p>If you have any questions, or wish to contact us, you can reach us here<br>
                    <a href="mailto:support@appxcel.com" style="color:#0084b5; text-decoration:none;">support@appxcel.com</a>
                 </p>
                 <p>Warm Regards!,  <br>
                 The WA Team.  
                 </p>
            </td>
            <td style="width:15px;">&nbsp;</td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td><img src="<?php echo $this->baseUrl ?>/images/mailer_format_07.png" width="648" height="113" style="vertical-align: top;" alt=""></td>
    </tr>
    <tr>
      <td>
      	<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
          <tr>
          	<td style="width:189px; height:119px;"><img src="<?php echo $this->baseUrl ?>/images/mailer_format_08.png" width="189" height="119" style="vertical-align: top;" alt=""></td>
			<td style="width:270px; height:91px;">
            	<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
                  <tr>
                    <td style="width:270px; height:91px;"><img src="<?php echo $this->baseUrl ?>/images/mailer_format_09.png" alt="" width="270" height="91" style="vertical-align: top;" usemap="#Map" border="0"></td>
                  </tr>
                  <tr>
                    <td style="width:270px; height:28px;"><img src="<?php echo $this->baseUrl ?>/images/mailer_format_11.png" width="270" height="28" style="vertical-align: top;" alt=""></td>
                  </tr>
                </table>
            </td>
            <td style="width:189px; height:119px;"><img src="<?php echo $this->baseUrl ?>/images/mailer_format_10.png" width="189" height="119" style="vertical-align: top;" alt=""></td>
          </tr>
        </table>
      </td>
    </tr>
  </tbody>
</table>
<map name="Map"><area shape="circle" coords="184,27,21" href="#">
	<area shape="circle" coords="135,27,21" href="#">
    <area shape="circle" coords="85,27,21" href="#">
</map>
</body>
</html>
