<html>
<head>
<title>WA</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body bgcolor="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">


<table width="648" border="0" align="center" cellpadding="0" cellspacing="0" style="font-family:Arial, sans-serif;">
  <tbody>
    <tr>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td>
      	<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">,
          <tr>
            <td style="width:24px; height:110px;"><img src="http://wa-app.com//images/mailer_format_01.png" style="vertical-align: top;" width="24" height="110" alt=""></td>
            <td align="left" valign="middle" style="background:#e6e6e6; border-bottom:1px solid #c9c9c9; height:109px;">
            
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tr>
                  <td align="left" valign="middle" style="height:108px; width:60px;"><img src="http://wa-app.com//images/logo.png" width="233" height="60" alt=""/></td>
                </tr>
            </table></td>
            <td style="width:24px; height:110px;"><img src="http://wa-app.com//images/mailer_format_03.png" width="24" height="110" style="vertical-align: top;" alt=""></td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td>
      
      	<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
          <tr>
            <td style="width:12px;">&nbsp;</td>
            <td style="background:#f2f2f2; padding:20px; font-size:16px; color:#333333; line-height:22px;">
                <p>Dear WA-user,</p>
                <p>Within the next 24hours we will release a stabilised “All-in-WA” version both on iOS and Android. </p>
                <p>In order to improve our services we need to delete your account and for one time only, we kindly request you to delete the current version of the app from your phone and reinstall our new version after we send you a new link. 
                <p>Thank you for your support and understanding.</p>
                <p>WA-team</p>
            </td>
            <td style="width:15px;">&nbsp;</td>
          </tr>
            
          <tr>
            <td style="width:12px;">&nbsp;</td>
            <td style="background:#f2f2f2; padding:20px; font-size:16px; color:#333333; line-height:22px;">
             <p>Cher membre WA, </p>
             <p>dans les prochaines 24 heures, nous allons sortir une version stabilisée de “All-in-WA" à la fois sur iOS et Android. Afin d'améliorer nos services, nous devons supprimer votre compte et a cet effet, pour une fois seulement, nous vous prions de supprimer la version actuelle de l'appli de votre téléphone et de la réinstaller dès que nous vous enverrons le nouveau lien. Nous vous remercions pour votre soutien et votre compréhension.</p>
             <p>WA-team</p>
            </td>
            <td style="width:15px;">&nbsp;</td>
          </tr>
          
          <tr>
            <td style="width:12px;">&nbsp;</td>
            <td style="background:#f2f2f2; padding:20px; font-size:16px; color:#333333; line-height:22px;">
                <p>Caro Utente-WA,</p>
                <p>nelle prossime 24 ore ci rilascerà una versione stabilizzata di "All-in-WA", sia su iOS e sia su Android. Al fine di migliorare i nostri servizi abbiamo bisogno di cancellare il tuo conto e per una sola volta, vi preghiamo di cancellare la versione corrente dell’app dal tuo telefono e reinstallarlo quando vi inviamo un nuovo collegamento. Grazie per il vostro sostegno e comprensione. 
                <p>WA-team</p>
            </td>
            <td style="width:15px;">&nbsp;</td>
          </tr>
          
          <tr>
            <td style="width:12px;">&nbsp;</td>
            <td style="background:#f2f2f2; padding:20px; font-size:16px; color:#333333; line-height:22px;">
                <p>Değerli WA-kullanıcısı,</p>
                <p>önümüzdeki 24 saat içerisinde IOS ve Android olmak üzere her iki platformda da ‘’All-in-WA’’ yeni sürümünü kullanıma sunacağız.Buna ek olarak servislerimizi geliştirmemiz ve sizlere daha iyi hizmet sağlayabilmemiz adına, bir defaya mahsus olmak üzere hesabınızı ve telefonunuzda kullandığınız uygulama sürümünü silip, sizinle yeni sürümümüzün bağlantısını paylaştığımızda tekrar yüklemenizi rica ediyoruz. 
                    Tüm anlayışınız ve desteğiniz için teşekkür ederiz.</p>
                <p>WA-takımı</p>
            </td>
            <td style="width:15px;">&nbsp;</td>
          </tr>
          
        </table>
      
      </td>
    </tr>
    <tr>
      <td><img src="http://wa-app.com/images/mailer_format_07.png" width="648" height="113" style="vertical-align: top;" alt=""></td>
    </tr>
    
    <tr>
      <td>
      	<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
          <tr>
          	<td style="width:189px; height:119px;"><img src="http://wa-app.com//images/mailer_format_08.png" width="189" height="119" style="vertical-align: top;" alt=""></td>
			<td style="width:270px; height:91px;">
            	<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
                  <tr>
                    <td style="width:270px; height:91px;"><img src="http://wa-app.com//images/mailer_format_09.png" alt="" width="270" height="91" style="vertical-align: top;" usemap="#Map" border="0"></td>
                  </tr>
                  <tr>
                    <td style="width:270px; height:28px;"><img src="http://wa-app.com//images/mailer_format_11.png" width="270" height="28" style="vertical-align: top;" alt=""></td>
                  </tr>
                </table>
            </td>
            <td style="width:189px; height:119px;"><img src="http://wa-app.com//images/mailer_format_10.png" width="189" height="119" style="vertical-align: top;" alt=""></td>
          </tr>
        </table>
      </td>
    </tr>
  </tbody>
</table>

<map name="Map"><area shape="circle" coords="184,27,21" href=mailto:"support@wa-app.com">
	<area shape="circle" coords="135,27,21" href="http://www.twitter.com/waapptweet">
    <area shape="circle" coords="85,27,21" href="http://www.facebook.com/waappbook">
</map>
</body>
</html>