<html>
<head>
<title>WA</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body bgcolor="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">


<table width="648" border="0" align="center" cellpadding="0" cellspacing="0" style="font-family:Arial, sans-serif;">
  <tbody>
    <tr>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td>
      	<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">,
          <tr>
            <td style="width:24px; height:110px;"><img src="http://wa-app.com//images/mailer_format_01.png" style="vertical-align: top;" width="24" height="110" alt=""></td>
            <td align="left" valign="middle" style="background:#e6e6e6; border-bottom:1px solid #c9c9c9; height:109px;">
            
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tr>
                  <td align="left" valign="middle" style="height:108px; width:60px;"><img src="http://wa-app.com//images/logo.png" width="233" height="60" alt=""/></td>
                </tr>
            </table></td>
            <td style="width:24px; height:110px;"><img src="http://wa-app.com//images/mailer_format_03.png" width="24" height="110" style="vertical-align: top;" alt=""></td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td>
      
      	<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
          <tr>
            <td style="width:12px;">&nbsp;</td>
            <td style="background:#f2f2f2; padding:20px; font-size:16px; color:#333333; line-height:22px;">
                <p>Dear WA-user,</p>
                <p>The new stabilised “All-in-WA” version is now available both on iOS and Android platforms. You may reinstall now by following your link and recreate a new account.</p>  
                <p>Thank you for your continuous support and understanding. 
                <p>For iOS please go to: <a target="_blank" href='https://itunes.apple.com/us/app/wa-app/id982136038?ls=1&mt=8'>https://itunes.apple.com/us/app/wa-app/id982136038?ls=1&mt=8</a></p>
                <p>For Android please go to:  <a target="_blank" href='https://play.google.com/store/apps/details?id=com.wa_app'>https://play.google.com/store/apps/details?id=com.wa_app<a></p>
                            <p>Thank you.</p> 
                            <p>WA-team</p>
            </td>
            <td style="width:15px;">&nbsp;</td>
          </tr>
            
          <tr>
            <td style="width:12px;">&nbsp;</td>
            <td style="background:#f2f2f2; padding:20px; font-size:16px; color:#333333; line-height:22px;">
                <p>Gentile Utente-WA,</p>
                <p>la nuova versione stabilizzata di "All-in-WA" ora è disponibile sia su iOS sia su Android. È possibile reinstallare ora seguendo il tuo link e ricreare un nuovo conto. Grazie per il vostro sostegno e comprensione.</p>
                <p>Per iOS: <a target="_blank" href='https://itunes.apple.com/us/app/wa-app/id982136038?ls=1&mt=8'>https://itunes.apple.com/us/app/wa-app/id982136038?ls=1&mt=8</a></p>
                <p>Per Android: <a target="_blank" href='https://play.google.com/store/apps/details?id=com.wa_app'>https://play.google.com/store/apps/details?id=com.wa_app</a></p> 
                <p>Grazie.</p> 
                <p>WA-team.</p>
            </td>
            <td style="width:15px;">&nbsp;</td>
          </tr>
          
          <tr>
            <td style="width:12px;">&nbsp;</td>
            <td style="background:#f2f2f2; padding:20px; font-size:16px; color:#333333; line-height:22px;">
                <p>Değerli WA-kullanıcısı,</p>
                <p>‘’All-in-WA’’ geliştirilmiş yeni sürümü ile IOS ve Android olmak üzere her iki platformda da kullanımınıza hazır. Aşağıdaki linklerden uygulamayı yeniden yükleyebilir ve yeni hesabınızı oluşturabilirsiniz. Tüm desteğiniz ve anlayışınız için teşekkür ederiz.</p>
                <p>IOS için buradan lütfen: <a target="_blank" href='https://itunes.apple.com/us/app/wa-app/id982136038?ls=1&mt=8'>https://itunes.apple.com/us/app/wa-app/id982136038?ls=1&mt=8</a></p>
                <p>Android için buradan lütfen: <a target="_blank" href='https://play.google.com/store/apps/details?id=com.wa_app'>https://play.google.com/store/apps/details?id=com.wa_app</a></p> 
                <p>Teşekkürler</p> 
                <p>WA-takımı</p>
            </td>
            <td style="width:15px;">&nbsp;</td>
          </tr>
          
          <tr>
            <td style="width:12px;">&nbsp;</td>
            <td style="background:#f2f2f2; padding:20px; font-size:16px; color:#333333; line-height:22px;">
                <p>Cher membre WA,</p> 
                <p>la nouvelle version stabilisée de “All-in-WA" est maintenant disponible à la fois sur les plates-formes iOS et Android. Vous pouvez réinstaller maintenant en suivant votre lien et recréer un nouveau compte. Nous vous remercions de votre soutien ainsi que de votre compréhension. 
                <p>Pour iOS s'il vous plaît, suivez ce lien: <a target="_blank" href='https://itunes.apple.com/us/app/wa-app/id982136038?ls=1&mt=8'>https://itunes.apple.com/us/app/wa-app/id982136038?ls=1&mt=8</a> </p>
                <p>Et pour Android: <a target="_blank" href='https://play.google.com/store/apps/details?id=com.wa_app'>https://play.google.com/store/apps/details?id=com.wa_app</a></p> 
                <p>Merci.</p> 
                <p>WA-team.</p>
            </td>
            <td style="width:15px;">&nbsp;</td>
          </tr>
          
        </table>
      
      </td>
    </tr>
    <tr>
      <td><img src="http://wa-app.com/images/mailer_format_07.png" width="648" height="113" style="vertical-align: top;" alt=""></td>
    </tr>
    
    <tr>
      <td>
      	<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
          <tr>
          	<td style="width:189px; height:119px;"><img src="http://wa-app.com//images/mailer_format_08.png" width="189" height="119" style="vertical-align: top;" alt=""></td>
			<td style="width:270px; height:91px;">
            	<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
                  <tr>
                    <td style="width:270px; height:91px;"><img src="http://wa-app.com//images/mailer_format_09.png" alt="" width="270" height="91" style="vertical-align: top;" usemap="#Map" border="0"></td>
                  </tr>
                  <tr>
                    <td style="width:270px; height:28px;"><img src="http://wa-app.com//images/mailer_format_11.png" width="270" height="28" style="vertical-align: top;" alt=""></td>
                  </tr>
                </table>
            </td>
            <td style="width:189px; height:119px;"><img src="http://wa-app.com//images/mailer_format_10.png" width="189" height="119" style="vertical-align: top;" alt=""></td>
          </tr>
        </table>
      </td>
    </tr>
  </tbody>
</table>

<map name="Map"><area shape="circle" coords="184,27,21" href=mailto:"support@wa-app.com">
	<area shape="circle" coords="135,27,21" href="http://www.twitter.com/waapptweet">
    <area shape="circle" coords="85,27,21" href="http://www.facebook.com/waappbook">
</map>
</body>
</html>