<!--Breadcrumb Starts-->
<div class="breadcrumb clearfix">
    <div class="col-xs-12">
        <a href="#">Home</a>
        <img src="/new_images/arrow_bred.png" width="22" height="9"/>
        <span>Received Testaments</span>    
    </div>
</div>
<!--Breadcrumb Ends-->

<!--Page Content Starts-->
<div class="content clearfix myTestament">
    <div class="col-xs-12">
        <h2>Received Testaments</h2>
        <table class="listing" border="0" cellpadding="0" cellspacing="0" width="100%">
            <tr><th>Testament Name :</th></tr>
            <tr><td>Testament 1</td></tr>
            <tr><td>Testament 1</td></tr>
            <tr><td>Testament 1</td></tr>
            <tr><td>Testament 1</td></tr>
            <tr><td>Testament 1</td></tr>
        </table>

        <h2>Vital check notification</h2>
        <table class="listing" border="0" cellpadding="0" cellspacing="0" width="100%">
            <tr><td>First :</td></tr>
            <tr><td>First :</td></tr>
            <tr><td>First :</td></tr>
            <tr><td>First :</td></tr>
            <tr><td>First :</td></tr>
        </table>

        <h2>Whom am I trustee of</h2>
        <table class="listing" border="0" cellpadding="0" cellspacing="0" width="100%">
            <tr><td>First :</td></tr>
            <tr><td>First :</td></tr>
            <tr><td>First :</td></tr>
            <tr><td>First :</td></tr>
            <tr><td>First :</td></tr>
        </table>
    </div>
 
    <div class="col-sm-12">
        <button type="button" class="btn">DELIVER NOW</button>
        <button type="button" class="btn">DECEASED</button>
    </div>
</div>
<!--Page Content Ends-->  